name: NuGet custom release

on:
  push:
    branches:
      - release-openur

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.variables.outputs.package_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install xmllint
        run: |
          sudo apt update
          sudo apt install --yes --no-install-suggests --no-install-recommends libxml2-utils

      - name: Setup variables
        id: variables
        shell: bash
        run: |
          PACKAGE_VERSION=$(xmllint --xpath '/*[local-name()="Project"]/*[local-name()="PropertyGroup"]/*[local-name()="PackageVersion"]/text()' FFMpegCore/FFMpegCore.csproj)

          echo "package_version=${PACKAGE_VERSION}" >> "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@ae28d57dabbb148eff63170b6bf7f2b60062cbae # 1.1.0
        with:
          version: '8.0'
          token: ${{ github.token }}

      - name: Test with dotnet
        run: >-
          dotnet test FFMpegCore.sln 
          --collect "XPlat Code Coverage" 
          --logger GitHubActions 

  package:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'

    - name: Build solution
      env:
        OWNER: ${{ github.repository_owner }}
      run: >-
        dotnet pack FFMpegCore/FFMpegCore.csproj 
        -c Release 
        -p:IncludeSymbols=false 
        -p:PackageId=${{ env.OWNER }}.FFMpegCore 
        -p:PackageVersion=${{ needs.prepare.outputs.package_version }}.${{ github.run_number }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: nupkg/*.nupkg
        if-no-files-found: error

  publish:
    needs:
      - test
      - package
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Download packages artifacts
        uses: actions/download-artifact@v5
        with:
          name: packages
          path: packages

      - name: Push to GitHub
        shell: bash
        run: >-
          dotnet nuget push
          packages/*.nupkg
          --no-symbols
          --skip-duplicate
          --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          --api-key ${{ secrets.GITHUB_TOKEN }}
